name: logitrack
description: Aplicativo de rastreamento de entregas para empresa de logística.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11
  badges: ^3.0.0
  provider: ^6.0.5

  # Ícones e UI
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  intl: ^0.18.1

  # Armazenamento local e persistência
  sqflite: ^2.3.0
  shared_preferences: ^2.2.1
  path_provider: ^2.1.2
  path: ^1.9.0

  # Recursos do dispositivo
  image_picker: ^1.0.4
  location: ^5.0.3
  camera: ^0.10.5+4

  # Notificações
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2

  # Estado

  # Conectividade e rede
  http: ^1.1.0
  connectivity_plus: ^5.0.2

  # Utilitários
  uuid: ^3.0.7
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
